version: '3'

services:

  #sql server service
  sql-server3:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1446:1433" # map host port 1433 to container port 1433
    environment:
      - accept_eula=y
      - sa_password=pa55w0rd2019
  
# .NET Core Web API Service
  web-api:
    build: . # Path to your Dockerfile for the Web API
    ports:
      - "8090:80" # Map host port 5000 to container port 80
    depends_on:
      - sql-server3
    environment:
      - PasswordConnection=true  
      - DBServer=sql-server3
      - DBPort=1433
      
 

 
